---

- src: "https://github.com/artefactual-labs/ansible-elasticsearch"
  version: "master"
  name: "elasticsearch"
  path: "roles/"

- src: "https://github.com/artefactual-labs/ansible-percona"
  version: "master"
  name: "percona"
  path: "roles/"

- src: "https://github.com/artefactual-labs/ansible-percona-client"
  version: "master"
  name: "percona-client"
  path: "roles/"

- src: "https://github.com/artefactual-labs/ansible-memcached"
  version: "master"
  name: "memcached"
  path: "roles/"

- src: "https://github.com/artefactual-labs/ansible-gearman"
  version: "master"
  name: "gearman"
  path: "roles/"

- src: "https://github.com/artefactual-labs/ansible-nginx"
  version: "master"
  name: "nginx"
  path: "roles/"

- src: "https://github.com/artefactual-labs/ansible-atom"
  version: "master"
  name: "atom"
  path: "roles/"
