---
- hosts: "atom-local"

  pre_tasks:

    - include_vars: "group_vars/all/atom.yml"
      tags:
        - "always"

  roles:

    - role: "elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"

    - role: "percona"
      become: "yes"
      tags:
        - "percona"

    - role: "memcached"
      become: "yes"
      tags:
        - "memcached"

    - role: "gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "nginx"
      become: "yes"
      tags:
        - "nginx"

    - role: "atom"
      become: "yes"
      tags:
        - "atom"